### ISSUE TITLE
Port to 2.0.1: TagHelper error: A local or parameter named '__model' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter

### ISSUE THREAD

**Issue by Eilon** [aspnet/Razor#1618]
Port this fix to 2.0.1: https://github.com/aspnet/Razor/issues/1614

**Comment by NTaylorMullen** [comment]
Will complete this work when we have 2.0.1 infrastructure in place.

**Comment by bdominguez** [comment]
Estimated date for release? This is a show stopper for me on upgrading to 2.0.

**Comment by Eilon** [comment]
@bdominguez we plan to release this in mid-September. Hard to pin down an exact date. However, we'll have pre-release builds of the patch before then, and we'll share details about that once the builds are ready.

**Comment by bdominguez** [comment]
@Eilon thanks.

**Comment by Gaelmart** [comment]
This has stopped 6 months of work dead at the last step.
Is there a hack or ANYTHING that can get me past it.?

**Comment by Eilon** [comment]
For folks running into this, can you show what code you have in your `@section` so that we can try to offer workarounds? The exact workaround (if one is available) would depend on what code is in the section.

**Comment by Gaelmart** [comment]
The __model errors happen on the lines  and only errors on publish to Azure (it builds fine)
 `<label asp-for="Password" class="col-md-2 control-label"></label>
<span asp-validation-for="Password" class="text-danger"></span>
 <label asp-for="ConfirmPassword" class="col-md-3 control-label"></label>
<span asp-validation-for="ConfirmPassword" class="text-danger"></span>
 <span asp-validation-for="Terms" class="text-danger"></span>`




`@model iBasisMobileV14.Models.AccountViewModels.SignupViewModel
@{
    ViewData["Title"] = "iBASIS Spares Search";
}

@{
    Layout = "~/Views/Shared/_SignupLayout.cshtml";
}
@*This is due to Angular Universals prerendering,
    and things such as window and jQuery not being
    available on the server side.
    You can follow angular/universal#534 as we try to make these things
    available or at the very least ignored on
    the server side to prevent errors.For now you can remove the asp-prerender attribute on the Index View to
    disable server side rendering if you need these libraries to work for now.
*@


@*<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app>*@
@*<app>Loading...</app>*@

@*<script src="~/dist/vendor.js" asp-append-version="true">
    </script>*@

@section content{

    @*<router-outlet></router-outlet>*@
  @*@Html.RenderPartial("_partialSignup");*@

<div class="Header-staticArea">
    <span class="icon-globe" style="font-size: .9rem;"> </span> Boiler and Spares Information Services
</div>

<div class="Landing">

    <section class="normal-content ms-Grid">
        <div class="row">
            <div class="col-lg-12 ">
                <div class="stackable">
                    <div class="page-block">
                        <div class="page-inner">
                            @*<div class="p-sm">
                                    <h2 class="pheader" color="gray1">
                                        <span>
                                            Thank you for becoming an iBasis Member
                                        </span>
                                    </h2>
                                </div>*@
                            <div class="container-fluid">


                                <div class="page-center enter-details col-12 col-sm-8">
                                    <div class="" wrap="nowrap">
                                        <div class="text-content">
                                            <h3>
                                                Enter your details
                                            </h3>
                                            <div class="row">
                                                <div class="col-12">
                                                    
                                                    <form asp-controller="Signup" asp-action="Index" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">
                                                        <div class="form-group">
                                                            <label for="Fullname" class="col-md-2 control-label">Full name:</label>
                                                            <div class="col-md-10">
                                                                @Html.TextBoxFor(m => m.Fullname, new { @class = "form-control", @placeholder = "Enter Full Name" })
                                                                @*<input type="text" asp-for="PublicViewModel.SignupViewModel.Fullname" class="form-control" id="Fullname" placeholder="Enter Full Name">*@
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="SignupUsername" class="col-md-2 control-label">User name:</label>
                                                            <div class="col-md-10">
                                                                @Html.TextBoxFor(m => m.Username, new { @class = "form-control", @placeholder = "Choose a User Name" })
                                                                @*<input type="text" class="form-control" id="SignupUsername" placeholder="Choose a User Username">*@
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="Email" class="col-md-2 control-label">Email address:</label>
                                                            <div class="col-md-10">
                                                                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "Enter email", @id = "Email" })
                                                                @*< input type="email" asp-for="SignupEmail" class="form-control" id="SignupEmail" aria-describedby="emailHelp" placeholder="Enter email">*@
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label asp-for="Password" class="col-md-2 control-label"></label>
                                                            <div class="col-md-10">
                                                                @Html.TextBoxFor(m => m.Password, new { @class = "form-control", @placeholder = "Choose Password", @id = "Password" })
                                                                @*<input asp-for="SignupPassword" class="form-control" />*@
                                                                <span asp-validation-for="Password" class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label asp-for="ConfirmPassword" class="col-md-3 control-label"></label>
                                                            <div class="col-md-10">
                                                                @Html.TextBoxFor(m => m.ConfirmPassword, new { @class = "form-control", @placeholder = "Retype Password" })
                                                                @*<input asp-for="SignupConfirmPassword" class="form-control" />*@
                                                                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                        <div class="form-check">
                                                            <label class="form-check-label">
                                                                @Html.CheckBoxFor(m => m.Terms, new { @class = "form-check-input", })
                                                                @*<input asp-for="Terms"   type="checkbox" class="form-check-input">*@
                                                                I aggree to iBasis Terms & conditions
                                                            </label>
                                                            <span asp-validation-for="Terms" class="text-danger"></span>
                                                        </div>
                                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                                        <button type="submit" class="btn btn-primary">Submit</button>
                                                    </form>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </section>
</div>


}
   


@section scripts {
    @*<script src="~/dist/main-client.js" asp-append-version="true">
        </script>*@

    @*<script src="~/lib/jasny-bootstrap/js/jasny-bootstrap.js" asp-append-version="true">
        </script>*@
    <script src="~/dist/static/js/libs/jquery.min.js">
    </script>
    <script src="~/dist/static/js/libs/tether.min.js">
    </script>
    <script src="~/dist/static/js/libs/bootstrap.min.js">
    </script>
    <script src="~/dist/static/js/app.js">
    </script>

    <script src="~/js/site.js" asp-append-version="true">
    </script>
}
`

**Comment by Eilon** [comment]
@Gaelmart thanks. @NTaylorMullen - any idea if there's a workaround that could be used for this?

**Comment by NTaylorMullen** [comment]
@Gaelmart one workaround you could do would be to throw all that TagHelper code that utilizes `asp-for` into a partial. I know it isn't ideal but it will work! 😄

**Comment by Eilon** [comment]
@NTaylorMullen ah that's probably a pretty good workaround that should work in most cases, though it's of course a bit messy.

**Comment by Eilon** [comment]
This patch bug is **approved** for the 2.0.x patch. Please send a PR to the `feature/2.0.1` branch and get it reviewed and merged. When we have the `rel/2.0.1` branches ready please port the commit to that branch.

**Comment by Eilon** [comment]
@ajaybhargavb - I reassigned this to you because @NTaylorMullen is still out.

**Comment by ajaybhargavb** [comment]
888e6bfc0009c0b2e75a31bd11d93875d0b6c2ff

**Comment by rajsingh216** [comment]
Please may I ask how can we get the fix?

**Comment by poke** [comment]
@rajsingh216 Update to version 2.0.1 once it’s released…

**Comment by poke** [comment]
@Eilon [In response to this comment](https://github.com/aspnet/Razor/issues/1614#issuecomment-326619975), is there any update on when 2.0.3 is going to release? I heard you had some release infrastructure problems which are resolved now, so do you have any date you can share? My team is getting a bit anxious since we are still holding off the upgrade because of this.

**Comment by Eilon** [comment]
@poke we unfortunately still have some infrastructure issues, but we are working right now on getting a preview build of 2.0.3 that people can try out. We don't have an exact date to share on the final release of 2.0.3 just yet.

**Comment by poke** [comment]
@Eilon A preview release would work just fine for me! Anything to allow me to move to 2.0 is great! Thanks for the update and good luck with your infrastructure :)

**Comment by Eilon** [comment]
@poke thanks, we're working through it! I will update all patch issues with download details when we have a build available to test.

**Comment by stefan505** [comment]
@Eilon any news on this? I had to jump through some hoops to successfully upgrade to 2.0 as a result of this.

**Comment by Eilon** [comment]
@stefan505 we're working on this right now. It's a bit complicated due to some infrastructure issues but it's a high priority for us.

**Comment by Eilon** [comment]
Hi, we have a public test feed that you can use to try out the ASP.NET/EF Core 2.0.3 patch!

To try out the pre-release patch, please refer to the following guide:
* https://github.com/aspnet/Announcements/issues/274 (info)
* https://github.com/aspnet/Home/issues/2254 (discussions and questions)

We are looking for feedback on this patch. We'd like to know if you have any issues with this patch by updating your apps and libraries to the latest packages and seeing if it fixes the issues you've had, or if it introduces any new issues. If you have any issues or questions, please reply on this issue to let us know as soon as possible.

Thanks,
Eilon
