### ISSUE TITLE
Updating to new SDK breaks Razor code generation

### ISSUE THREAD

**Issue by pakrym** [aspnet/Razor#2148]
MVC build fails with:
```
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\TagHelpersWebSite\obj\Release\netcoreapp2.0\Razor\Views\Home\ViewComponentTagHelpers.cs(39,25): error CS0400: The type or namespace name '__Generated__GenericViewComponentTagHelper' could not be found in the global namespace (are you missing an assembly reference?)
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\TagHelpersWebSite\obj\Release\netcoreapp2.0\Razor\Views\Home\ViewComponentTagHelpers.cs(41,25): error CS0400: The type or namespace name '__Generated__DanViewComponentTagHelper' could not be found in the global namespace (are you missing an assembly reference?)
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\TagHelpersWebSite\obj\Release\netcoreapp2.0\Razor\Views\Home\ViewComponentTagHelpers.cs(43,25): error CS0400: The type or namespace name '__Generated__CopyrightViewComponentTagHelper' could not be found in the global namespace (are you missing an assembly reference?)
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\TagHelpersWebSite\obj\Release\netcoreapp2.1\Razor\Views\Home\ViewComponentTagHelpers.cs(39,25): error CS0400: The type or namespace name '__Generated__GenericViewComponentTagHelper' could not be found in the global namespace (are you missing an assembly reference?)
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\TagHelpersWebSite\obj\Release\netcoreapp2.1\Razor\Views\Home\ViewComponentTagHelpers.cs(41,25): error CS0400: The type or namespace name '__Generated__DanViewComponentTagHelper' could not be found in the global namespace (are you missing an assembly reference?)
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\TagHelpersWebSite\obj\Release\netcoreapp2.1\Razor\Views\Home\ViewComponentTagHelpers.cs(43,25): error CS0400: The type or namespace name '__Generated__CopyrightViewComponentTagHelper' could not be found in the global namespace (are you missing an assembly reference?)
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\TagHelpersWebSite\obj\Release\net461\Razor\Views\Home\ViewComponentTagHelpers.cs(39,25): error CS0400: The type or namespace name '__Generated__GenericViewComponentTagHelper' could not be found in the global namespace (are you missing an assembly reference?)
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\TagHelpersWebSite\obj\Release\net461\Razor\Views\Home\ViewComponentTagHelpers.cs(41,25): error CS0400: The type or namespace name '__Generated__DanViewComponentTagHelper' could not be found in the global namespace (are you missing an assembly reference?)
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\TagHelpersWebSite\obj\Release\net461\Razor\Views\Home\ViewComponentTagHelpers.cs(43,25): error CS0400: The type or namespace name '__Generated__CopyrightViewComponentTagHelper' could not be found in the global namespace (are you missing an assembly reference?)
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\RazorPagesWebSite\Login.cshtml(2,7): error CS0103: The name 'Context' does not exist in the current context
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\RazorPagesWebSite\Show.cshtml(3,7): error CS0103: The name 'function' does not exist in the current context
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\RazorPagesWebSite\Login.cshtml(2,7): error CS0103: The name 'Context' does not exist in the current context
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\RazorPagesWebSite\Show.cshtml(3,7): error CS0103: The name 'function' does not exist in the current context
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\ErrorPageMiddlewareWebSite\Views\ErrorPageMiddleware\ParserError.cshtml(1,2): error RZ1006: The code block is missing a closing "}" character. Make sure you have a matching "}" character for all the "{" characters within this block, and that none of the "}" characters are being interpreted as markup.
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\ErrorPageMiddlewareWebSite\Views\ErrorPageMiddleware\ParserError.cshtml(1,2): error RZ1006: The code block is missing a closing "}" character. Make sure you have a matching "}" character for all the "{" characters within this block, and that none of the "}" characters are being interpreted as markup.
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\BasicWebSite\Views\RemoteAttribute_Home\Details.cshtml(5,58): error CS1503: Argument 2: cannot convert from 'out string' to 'out object'
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\BasicWebSite\Views\RemoteAttribute_Home\Details.cshtml(5,58): error CS1503: Argument 2: cannot convert from 'out string' to 'out object'
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\RazorPagesWebSite\Login.cshtml(2,7): error CS0103: The name 'Context' does not exist in the current context
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\RazorPagesWebSite\Show.cshtml(3,7): error CS0103: The name 'function' does not exist in the current context
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\BasicWebSite\Views\RemoteAttribute_Home\Details.cshtml(5,58): error CS1503: Argument 2: cannot convert from 'out string' to 'out object'
[11:59:00] Mvc | C:\b\w\7471ab17b6f47b37\modules\Mvc\test\WebSites\ErrorPageMiddlewareWebSite\Views\ErrorPageMiddleware\ParserError.cshtml(1,2): error RZ1006: The code block is missing a closing "}" character. Make sure you have a matching "}" character for all the "{" characters within this block, and that none of the "}" characters are being interpreted as markup.
[11:59:00] Mvc | 0 Warning(s)
[11:59:00] Mvc | 21 Error(s)

``` 

You can repro it localy by changing `korebuild-lock.txt` to version `2.1.0-preview2-15732`

/cc @JunTaoLuo  @ryanbrandenburg  @rynowak  @natemcmaster  @pranavkm

**Comment by rynowak** [comment]
@pranavkm - can you take a look at this since @ajaybhargavb is out? We could turn off compile on build as a temporary measure, but I don't want to lose track of the fact that we have test files with bugs in them.

**Comment by pranavkm** [comment]
Yup, looking

**Comment by pranavkm** [comment]
Have a PR out for this - https://github.com/aspnet/Mvc/pull/7464. Created a follow up item to investigate VCTH here: https://github.com/aspnet/Razor/issues/2150

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Mvc/commit/62fdf3a47217b2c03de8e0158e85c93dbb368f16.

**Comment by rynowak** [comment]
It looks like there's still an issue with the code generation for view component tag helpers. Self-assigning myself for investigation.

**Comment by rynowak** [comment]
This was fixed
